#:schema node_modules/wrangler/config-schema.json
name = "parliament-wow"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
main = "./dist/index.js"
assets = { directory = "./public" }


[observability]
enabled = true

[[kv_namespaces]]
binding = "SUMMARY_CACHE"
id = "49cc650aec244c6294881c898849d9d1"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "parliament-wow"
database_id = "f1ac1924-8d91-49dd-aada-6c616cfd45c8"
migrations_dir = "drizzle/"

[ai]
binding = "AI"