#:schema node_modules/wrangler/config-schema.json
name = "parliament-wow"
compatibility_date = "2024-09-25"

main = "./dist/index.js"
assets = { directory = "./public" }


[observability]
enabled = true
